import type { DomainEvent, ExternalEventProvenance } from "./domain-event.ts";

export class DomainEventValidationError extends Error { constructor(message: string) { super(message); this.name = "DomainEventValidationError"; } }
const ACTOR_TYPES = new Set(["USER", "CORE", "WORKER", "PROVIDER", "INTEGRATION", "MODULE", "SYSTEM"]);
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new DomainEventValidationError(`${label} must be an object`); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new DomainEventValidationError("domain event contains unsupported or missing fields"); }
function text(value: unknown, label: string, max = 512): string { if (typeof value !== "string" || value.length < 1 || value.length > max || value.includes("\0")) throw new DomainEventValidationError(`${label} is invalid`); return value; }
function opaque(value: unknown, label: string): string { const result = text(value, label, 256); if (!/^[A-Za-z0-9][A-Za-z0-9._:-]*$/u.test(result)) throw new DomainEventValidationError(`${label} is not an opaque identifier`); return result; }
function uuid7(value: unknown, label: string): string { const result = text(value, label, 36).toLowerCase(); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(result)) throw new DomainEventValidationError(`${label} must be UUIDv7`); return result; }
function timestamp(value: unknown, label: string): string { const result = text(value, label, 64); if (Number.isNaN(Date.parse(result))) throw new DomainEventValidationError(`${label} must be an ISO timestamp`); return result; }
function boundedPayload(value: unknown, depth = 0): unknown { if (depth > 8) throw new DomainEventValidationError("event payload nesting is too deep"); if (typeof value === "string") return text(value, "payload", 8192); if (typeof value === "number" || typeof value === "boolean" || value === null) return value; if (Array.isArray(value)) { if (value.length > 1024) throw new DomainEventValidationError("event payload array is too large"); return Object.freeze(value.map((item) => boundedPayload(item, depth + 1))); } const input = record(value, "payload"); if (Object.keys(input).length > 256) throw new DomainEventValidationError("event payload object is too large"); for (const key of Object.keys(input)) if (/(password|secret|token|private.?key|credential)/iu.test(key)) throw new DomainEventValidationError("secret-bearing event payload key is prohibited"); return Object.freeze(Object.fromEntries(Object.entries(input).map(([key, item]) => [text(key, "payload key", 256), boundedPayload(item, depth + 1)]))); }
export function validateDomainEvent(value: unknown): DomainEvent { const input = record(value, "domain event"); keys(input, ["eventId", "occurredAt", "type", "payloadVersion", "aggregateType", "aggregateId", "correlationId", "actorType", "payload"], ["causationId", "actorId"]); if (!Number.isSafeInteger(input.payloadVersion) || (input.payloadVersion as number) < 1) throw new DomainEventValidationError("payloadVersion is invalid"); if (!/^[a-z][a-z0-9]*(?:\.[a-z0-9]+)+$/u.test(String(input.type))) throw new DomainEventValidationError("event type must use stable dot notation"); if (typeof input.actorType !== "string" || !ACTOR_TYPES.has(input.actorType)) throw new DomainEventValidationError("actorType is invalid"); return Object.freeze({ eventId: uuid7(input.eventId, "eventId"), occurredAt: timestamp(input.occurredAt, "occurredAt"), type: text(input.type, "type", 256), payloadVersion: input.payloadVersion as number, aggregateType: opaque(input.aggregateType, "aggregateType"), aggregateId: opaque(input.aggregateId, "aggregateId"), correlationId: uuid7(input.correlationId, "correlationId"), ...(input.causationId === undefined ? {} : { causationId: uuid7(input.causationId, "causationId") }), actorType: input.actorType as DomainEvent["actorType"], ...(input.actorId === undefined ? {} : { actorId: opaque(input.actorId, "actorId") }), payload: boundedPayload(input.payload) }); }
export function validateExternalEventProvenance(value: unknown): ExternalEventProvenance { const input = record(value, "external event provenance"); keys(input, ["sourceType", "sourceId"], ["deduplicationKey"]); return Object.freeze({ sourceType: opaque(input.sourceType, "sourceType"), sourceId: opaque(input.sourceId, "sourceId"), ...(input.deduplicationKey === undefined ? {} : { deduplicationKey: text(input.deduplicationKey, "deduplicationKey", 1024) }) }); }
