import type { ConversationMessage, ConversationMessageRole, ConversationRecord, MemoryConfidence, MemoryRecord, MemoryRetrievalRequest, MemoryScope, MemoryScopeKind, MemoryRetrievalResult, RetentionAnchor, RetentionRecordType } from "./memory.ts";
import type { DataLocality, DataPolicy, DataSensitivity } from "./data.ts";

export class MemoryValidationError extends Error { constructor(message: string) { super(message); this.name = "MemoryValidationError"; } }
const SENSITIVITY = new Set<DataSensitivity>(["PUBLIC", "PRIVATE", "SENSITIVE", "SECRET"]);
const LOCALITY = new Set<DataLocality>(["LOCAL_ONLY", "ANY_APPROVED_PROVIDER"]);
const SCOPES = new Set<MemoryScopeKind>(["USER_GLOBAL", "PROJECT", "MISSION", "TASK", "SESSION"]);
const CONFIDENCE = new Set<MemoryConfidence>(["VERIFIED", "CONFIRMED", "INFERRED", "STALE"]);
const ROLES = new Set<ConversationMessageRole>(["USER", "ASSISTANT", "SYSTEM", "TOOL"]);
const RETENTION_TYPES = new Set<RetentionRecordType>(["CONVERSATION", "MESSAGE", "MEMORY", "AUDIT"]);
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new MemoryValidationError(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new MemoryValidationError("memory/conversation record contains unsupported or missing fields"); }
function text(value: unknown, label: string, max: number): string { if (typeof value !== "string" || value.length < 1 || value.length > max || value.includes("\0")) throw new MemoryValidationError(`${label} is invalid`); return value; }
function id(value: unknown, label: string): string { const result = text(value, label, 256); if (!/^[A-Za-z0-9][A-Za-z0-9._:-]*$/u.test(result)) throw new MemoryValidationError(`${label} is not an opaque identifier`); return result; }
function timestamp(value: unknown, label: string): string { const result = text(value, label, 64); if (Number.isNaN(Date.parse(result))) throw new MemoryValidationError(`${label} must be an ISO timestamp`); return result; }
function policy(value: unknown): DataPolicy { const input = record(value, "dataPolicy"); exact(input, ["sensitivity", "locality"]); if (typeof input.sensitivity !== "string" || !SENSITIVITY.has(input.sensitivity as DataSensitivity) || typeof input.locality !== "string" || !LOCALITY.has(input.locality as DataLocality)) throw new MemoryValidationError("dataPolicy is invalid"); if (input.sensitivity === "SECRET") throw new MemoryValidationError("SECRET conversation/memory content is not allowed in the normal store"); return Object.freeze({ sensitivity: input.sensitivity as DataSensitivity, locality: input.locality as DataLocality }); }
function version(value: unknown, label: string, minimum = 0): number { if (!Number.isSafeInteger(value) || (value as number) < minimum) throw new MemoryValidationError(`${label} is invalid`); return value as number; }
export function validateRetentionAnchor(value: unknown): RetentionAnchor { const input = record(value, "retention anchor"); exact(input, ["anchorId", "recordType", "recordId", "policyId", "retainUntil", "reason", "createdAt"]); if (typeof input.recordType !== "string" || !RETENTION_TYPES.has(input.recordType as RetentionRecordType)) throw new MemoryValidationError("retention recordType is invalid"); return Object.freeze({ anchorId: id(input.anchorId, "anchorId"), recordType: input.recordType as RetentionRecordType, recordId: id(input.recordId, "recordId"), policyId: id(input.policyId, "policyId"), retainUntil: timestamp(input.retainUntil, "retainUntil"), reason: text(input.reason, "reason", 512), createdAt: timestamp(input.createdAt, "createdAt") }); }
export function validateConversation(value: unknown): ConversationRecord { const input = record(value, "conversation"); exact(input, ["conversationId", "userId", "dataPolicy", "retentionAnchorId", "expectedVersion", "createdAt", "updatedAt"]); return Object.freeze({ conversationId: id(input.conversationId, "conversationId"), userId: id(input.userId, "userId"), dataPolicy: policy(input.dataPolicy), retentionAnchorId: id(input.retentionAnchorId, "retentionAnchorId"), expectedVersion: version(input.expectedVersion, "expectedVersion"), createdAt: timestamp(input.createdAt, "createdAt"), updatedAt: timestamp(input.updatedAt, "updatedAt") }); }
export function validateConversationMessage(value: unknown): ConversationMessage { const input = record(value, "conversation message"); exact(input, ["messageId", "conversationId", "role", "content", "dataPolicy", "createdAt"]); if (typeof input.role !== "string" || !ROLES.has(input.role as ConversationMessageRole)) throw new MemoryValidationError("conversation message role is invalid"); return Object.freeze({ messageId: id(input.messageId, "messageId"), conversationId: id(input.conversationId, "conversationId"), role: input.role as ConversationMessageRole, content: text(input.content, "content", 65536), dataPolicy: policy(input.dataPolicy), createdAt: timestamp(input.createdAt, "createdAt") }); }
export function validateMemory(value: unknown): MemoryRecord { const input = record(value, "memory"); exact(input, ["memoryId", "scope", "content", "confidence", "sourceType", "sourceId", "sourceRevision", "observedAt", "dataPolicy", "retentionAnchorId", "expectedVersion"], ["verifiedAt", "staleAt"]); const scope = record(input.scope, "memory scope"); exact(scope, ["kind"], ["scopeId"]); if (typeof scope.kind !== "string" || !SCOPES.has(scope.kind as MemoryScopeKind)) throw new MemoryValidationError("memory scope is invalid"); if (scope.kind !== "USER_GLOBAL" && scope.scopeId === undefined) throw new MemoryValidationError("scoped memory requires scopeId"); if (typeof input.confidence !== "string" || !CONFIDENCE.has(input.confidence as MemoryConfidence)) throw new MemoryValidationError("memory confidence is invalid"); return Object.freeze({ memoryId: id(input.memoryId, "memoryId"), scope: Object.freeze({ kind: scope.kind as MemoryScopeKind, ...(scope.scopeId === undefined ? {} : { scopeId: id(scope.scopeId, "scopeId") }) }) as MemoryScope, content: text(input.content, "content", 32768), confidence: input.confidence as MemoryConfidence, sourceType: id(input.sourceType, "sourceType"), sourceId: id(input.sourceId, "sourceId"), sourceRevision: version(input.sourceRevision, "sourceRevision", 1), observedAt: timestamp(input.observedAt, "observedAt"), ...(input.verifiedAt === undefined ? {} : { verifiedAt: timestamp(input.verifiedAt, "verifiedAt") }), ...(input.staleAt === undefined ? {} : { staleAt: timestamp(input.staleAt, "staleAt") }), dataPolicy: policy(input.dataPolicy), retentionAnchorId: id(input.retentionAnchorId, "retentionAnchorId"), expectedVersion: version(input.expectedVersion, "expectedVersion") }); }
function retrievalScope(value: unknown): MemoryScope { const input = record(value, "retrieval scope"); exact(input, ["kind"], ["scopeId"]); if (typeof input.kind !== "string" || !SCOPES.has(input.kind as MemoryScopeKind)) throw new MemoryValidationError("retrieval scope is invalid"); if (input.kind !== "USER_GLOBAL" && input.scopeId === undefined) throw new MemoryValidationError("scoped retrieval scope requires scopeId"); return Object.freeze({ kind: input.kind as MemoryScopeKind, ...(input.scopeId === undefined ? {} : { scopeId: id(input.scopeId, "scopeId") }) }); }
function stringArray(value: unknown, label: string, maxItems: number, maxLength: number): readonly string[] { if (!Array.isArray(value) || value.length > maxItems) throw new MemoryValidationError(`${label} is invalid`); const values = value.map((item) => text(item, label, maxLength)); if (new Set(values).size !== values.length) throw new MemoryValidationError(`${label} contains duplicates`); return Object.freeze(values); }
export function validateMemoryRetrievalRequest(value: unknown): MemoryRetrievalRequest { const input = record(value, "memory retrieval request"); exact(input, ["requestId", "applicableScopes", "queryTerms", "dataPolicy", "limit", "now", "authoritativeSourceIds"]); if (!Array.isArray(input.applicableScopes) || input.applicableScopes.length < 1 || input.applicableScopes.length > 16) throw new MemoryValidationError("applicableScopes is invalid"); const applicableScopes = Object.freeze(input.applicableScopes.map((item) => retrievalScope(item))); if (!Number.isSafeInteger(input.limit) || (input.limit as number) < 1 || (input.limit as number) > 64) throw new MemoryValidationError("memory retrieval limit is invalid"); return Object.freeze({ requestId: id(input.requestId, "requestId"), applicableScopes, queryTerms: stringArray(input.queryTerms, "queryTerms", 16, 128), dataPolicy: policy(input.dataPolicy), limit: input.limit as number, now: timestamp(input.now, "now"), authoritativeSourceIds: stringArray(input.authoritativeSourceIds, "authoritativeSourceIds", 64, 256) }); }
