import type { ProjectPolicyDecision, ProjectPolicyDecisionRequest, ProjectPolicyMutationGateResult, ProjectPolicySnapshotRecord, ProjectPolicySnapshotRevalidationRequest, ProjectPolicyTrustRecord, ProjectPolicyTrustState } from "./project-policy.ts";

export class ProjectPolicyValidationError extends Error { constructor(message: string) { super(message); this.name = "ProjectPolicyValidationError"; } }
export const PROJECT_POLICY_CANDIDATE_FILENAME = "AGENTS.md" as const;
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new ProjectPolicyValidationError(`${label} must be an object`); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new ProjectPolicyValidationError("project policy record contains unsupported or missing fields"); }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$/u.test(value)) throw new ProjectPolicyValidationError(`${label} is invalid`); return value; }
function text(value: unknown, label: string, max = 4096): string { if (typeof value !== "string" || value.length < 1 || value.length > max || value.includes("\0")) throw new ProjectPolicyValidationError(`${label} is invalid`); return value; }
function timestamp(value: unknown, label: string): string { const result = text(value, label, 64); if (Number.isNaN(Date.parse(result))) throw new ProjectPolicyValidationError(`${label} must be an ISO timestamp`); return result; }
function sha256(value: unknown, label: string): string { if (typeof value !== "string" || !/^[a-f0-9]{64}$/u.test(value)) throw new ProjectPolicyValidationError(`${label} must be a lowercase SHA-256 digest`); return value; }
function relativePath(value: unknown): string { const result = text(value, "canonicalRelativePath", 4096).replaceAll("\\", "/"); if (result.startsWith("/") || result.split("/").some((part) => part === ".." || part.length === 0)) throw new ProjectPolicyValidationError("canonical policy path must remain relative and traversal-free"); return result; }
export function validateProjectPolicyCandidatePath(value: unknown): string { const result = relativePath(value); if (result.split("/").at(-1) !== PROJECT_POLICY_CANDIDATE_FILENAME) throw new ProjectPolicyValidationError("only AGENTS.md is a supported project-policy candidate"); return result; }
export function evaluateProjectPolicyMutationGate(state: ProjectPolicyTrustState | undefined, consequential: boolean): ProjectPolicyMutationGateResult { if (!consequential || state === undefined || state === "TRUSTED" || state === "DISABLED_BY_USER") return Object.freeze({ status: "ALLOWED", ...(state === undefined ? {} : { policyState: state }) }); return Object.freeze({ status: "PROJECT_POLICY_DECISION_REQUIRED", policyState: state }); }
export function validateProjectPolicyDecisionRequest(value: unknown): ProjectPolicyDecisionRequest { const input = record(value, "project policy decision"); keys(input, ["policyTrustId", "expectedRevision", "decision", "userId", "sessionId", "now"]); if (!Number.isSafeInteger(input.expectedRevision) || (input.expectedRevision as number) < 1) throw new ProjectPolicyValidationError("expected policy revision is invalid"); const decision = input.decision as ProjectPolicyDecision; if (!["TRUST", "DISABLE", "REVOKE"].includes(decision)) throw new ProjectPolicyValidationError("project policy decision is invalid"); return Object.freeze({ policyTrustId: id(input.policyTrustId, "policyTrustId"), expectedRevision: input.expectedRevision as number, decision, userId: id(input.userId, "userId"), sessionId: id(input.sessionId, "sessionId"), now: timestamp(input.now, "now") }); }
function canonicalScope(value: string): string { return value.replaceAll("\\", "/").replace(/\/+$/u, ""); }
function scopeDepth(value: string): number { return canonicalScope(value).split("/").filter((part) => part.length > 0).length; }
function scopeContains(scope: string, target: string): boolean { const normalizedScope = canonicalScope(scope); const normalizedTarget = canonicalScope(target); return normalizedTarget === normalizedScope || normalizedTarget.startsWith(`${normalizedScope}/`); }
export function resolveApplicableTrustedProjectPolicies(values: readonly unknown[], targetCanonicalPath: unknown): readonly ProjectPolicyTrustRecord[] {
  const target = text(targetCanonicalPath, "targetCanonicalPath", 4096);
  const records = values.map(validateProjectPolicyTrustRecord).filter((policy) => policy.state === "TRUSTED" && scopeContains(policy.canonicalScopeRoot, target));
  const scopes = new Map<string, ProjectPolicyTrustRecord>();
  for (const policy of records) {
    const scope = canonicalScope(policy.canonicalScopeRoot);
    if (scopes.has(scope)) throw new ProjectPolicyValidationError("multiple trusted project policies apply at the same scope");
    scopes.set(scope, policy);
  }
  return Object.freeze([...scopes.values()].sort((left, right) => {
    const depth = scopeDepth(left.canonicalScopeRoot) - scopeDepth(right.canonicalScopeRoot);
    return depth !== 0 ? depth : left.policyTrustId.localeCompare(right.policyTrustId);
  }));
}
export function validateProjectPolicyTrustRecord(value: unknown): ProjectPolicyTrustRecord { const input = record(value, "project policy trust record"); keys(input, ["policyTrustId", "projectId", "canonicalRelativePath", "canonicalScopeRoot", "contentSha256", "state", "revision"], ["gitBlobOid", "sourceCommit", "acceptedAt", "acceptedSessionId"]); if (!Number.isSafeInteger(input.revision) || (input.revision as number) < 1) throw new ProjectPolicyValidationError("policy revision is invalid"); const state = input.state as ProjectPolicyTrustState; if (!["UNTRUSTED_CANDIDATE", "TRUSTED", "CHANGED_REVIEW_REQUIRED", "DISABLED_BY_USER", "REVOKED"].includes(state)) throw new ProjectPolicyValidationError("policy trust state is invalid"); if (state === "TRUSTED" && (input.acceptedAt === undefined || input.acceptedSessionId === undefined)) throw new ProjectPolicyValidationError("trusted policy requires explicit acceptance evidence"); return Object.freeze({ policyTrustId: id(input.policyTrustId, "policyTrustId"), projectId: id(input.projectId, "projectId"), canonicalRelativePath: validateProjectPolicyCandidatePath(input.canonicalRelativePath), canonicalScopeRoot: text(input.canonicalScopeRoot, "canonicalScopeRoot", 4096), contentSha256: sha256(input.contentSha256, "contentSha256"), ...(input.gitBlobOid === undefined ? {} : { gitBlobOid: text(input.gitBlobOid, "gitBlobOid", 128) }), ...(input.sourceCommit === undefined ? {} : { sourceCommit: text(input.sourceCommit, "sourceCommit", 128) }), state, ...(input.acceptedAt === undefined ? {} : { acceptedAt: timestamp(input.acceptedAt, "acceptedAt") }), ...(input.acceptedSessionId === undefined ? {} : { acceptedSessionId: id(input.acceptedSessionId, "acceptedSessionId") }), revision: input.revision as number }); }
export function validateProjectPolicySnapshot(value: unknown): ProjectPolicySnapshotRecord { const input = record(value, "project policy snapshot"); keys(input, ["snapshotId", "projectId", "attemptId", "createdAt", "policies"]); if (!Array.isArray(input.policies) || input.policies.length > 1024) throw new ProjectPolicyValidationError("policy snapshot policies are invalid"); const policies = input.policies.map((item) => { const policy = record(item, "policy snapshot entry"); keys(policy, ["policyTrustId", "revision", "contentSha256"]); if (!Number.isSafeInteger(policy.revision) || (policy.revision as number) < 1) throw new ProjectPolicyValidationError("snapshot policy revision is invalid"); return Object.freeze({ policyTrustId: id(policy.policyTrustId, "policyTrustId"), revision: policy.revision as number, contentSha256: sha256(policy.contentSha256, "snapshot contentSha256") }); }); if (new Set(policies.map((item) => item.policyTrustId)).size !== policies.length) throw new ProjectPolicyValidationError("policy snapshot contains duplicate trust records"); return Object.freeze({ snapshotId: id(input.snapshotId, "snapshotId"), projectId: id(input.projectId, "projectId"), attemptId: id(input.attemptId, "attemptId"), createdAt: timestamp(input.createdAt, "createdAt"), policies: Object.freeze(policies) }); }
export function validateProjectPolicySnapshotRevalidationRequest(value: unknown): ProjectPolicySnapshotRevalidationRequest { const input = record(value, "project policy snapshot revalidation request"); keys(input, ["snapshotId", "projectId", "attemptId", "trigger"]); if (!["NEW_ATTEMPT", "RESUMING", "CONSEQUENTIAL_ACTION"].includes(input.trigger as string)) throw new ProjectPolicyValidationError("project policy snapshot revalidation trigger is invalid"); return Object.freeze({ snapshotId: id(input.snapshotId, "snapshotId"), projectId: id(input.projectId, "projectId"), attemptId: id(input.attemptId, "attemptId"), trigger: input.trigger as ProjectPolicySnapshotRevalidationRequest["trigger"] }); }
