import type { ReleaseTrustRecord, TrustedUpdateMetadataRecord, TrustedUpdateRoleMetadata, UpdateIncidentRecord, UpdateOperationRecord } from "./update-trust.ts";

export class UpdateTrustValidationError extends Error { constructor(message: string) { super(message); this.name = "UpdateTrustValidationError"; } }
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new UpdateTrustValidationError(`${label} must be an object`); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new UpdateTrustValidationError("update trust record contains unsupported or missing fields"); }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$/u.test(value)) throw new UpdateTrustValidationError(`${label} is invalid`); return value; }
function text(value: unknown, label: string, max = 4096): string { if (typeof value !== "string" || value.length < 1 || value.length > max || value.includes("\0")) throw new UpdateTrustValidationError(`${label} is invalid`); return value; }
function uint(value: unknown, label: string): string { if (typeof value !== "string" || !/^(0|[1-9][0-9]*)$/u.test(value) || value.length > 20) throw new UpdateTrustValidationError(`${label} must be a canonical uint64 string`); return value; }
function sha(value: unknown, label: string): string { if (typeof value !== "string" || !/^[a-f0-9]{64}$/u.test(value)) throw new UpdateTrustValidationError(`${label} must be a lowercase SHA-256 digest`); return value; }
function timestamp(value: unknown, label: string): string { const result = text(value, label, 64); if (Number.isNaN(Date.parse(result))) throw new UpdateTrustValidationError(`${label} must be an ISO timestamp`); return result; }
function strings(value: unknown, label: string): readonly string[] { if (!Array.isArray(value) || value.length < 1 || value.some((item) => typeof item !== "string") || new Set(value).size !== value.length) throw new UpdateTrustValidationError(`${label} must be a unique non-empty string array`); return Object.freeze(value.map((item) => id(item, label))); }
function enumValue<T extends string>(value: unknown, values: readonly T[], label: string): T { if (typeof value !== "string" || !values.includes(value as T)) throw new UpdateTrustValidationError(`${label} is invalid`); return value as T; }
function role(value: unknown): TrustedUpdateRoleMetadata { const input = record(value, "TUF role"); keys(input, ["version", "sha256", "keyIds", "threshold", "custodyClass"]); if (!Number.isSafeInteger(input.threshold) || (input.threshold as number) < 1) throw new UpdateTrustValidationError("TUF role threshold is invalid"); const keyIds = strings(input.keyIds, "role key IDs"); if ((input.threshold as number) > keyIds.length) throw new UpdateTrustValidationError("TUF role threshold exceeds key count"); return Object.freeze({ version: uint(input.version, "role version"), sha256: sha(input.sha256, "role metadata hash"), keyIds, threshold: input.threshold as number, custodyClass: text(input.custodyClass, "custodyClass") }); }
export function validateTrustedUpdateMetadata(value: unknown): TrustedUpdateMetadataRecord { const input = record(value, "trusted update metadata"); keys(input, ["metadataId", "tufSpecVersion", "trustedRootVersion", "trustedRootSha256", "roles", "metadataVersion", "metadataSha256", "minimumSecurityEpoch", "observedAt", "expiresAt", "state"]); if (input.tufSpecVersion !== "1.0.35") throw new UpdateTrustValidationError("unsupported TUF specification profile"); const roles = record(input.roles, "TUF roles"); keys(roles, ["root", "targets", "snapshot", "timestamp", "modules"]); return Object.freeze({ metadataId: id(input.metadataId, "metadataId"), tufSpecVersion: "1.0.35", trustedRootVersion: uint(input.trustedRootVersion, "trustedRootVersion"), trustedRootSha256: sha(input.trustedRootSha256, "trustedRootSha256"), roles: Object.freeze({ root: role(roles.root), targets: role(roles.targets), snapshot: role(roles.snapshot), timestamp: role(roles.timestamp), modules: role(roles.modules) }), metadataVersion: uint(input.metadataVersion, "metadataVersion"), metadataSha256: sha(input.metadataSha256, "metadataSha256"), minimumSecurityEpoch: uint(input.minimumSecurityEpoch, "minimumSecurityEpoch"), observedAt: timestamp(input.observedAt, "observedAt"), expiresAt: timestamp(input.expiresAt, "expiresAt"), state: enumValue(input.state, ["TRUSTED", "STALE", "UNAVAILABLE", "DEGRADED"], "metadata state") }); }
export function validateReleaseTrustRecord(value: unknown): ReleaseTrustRecord { const input = record(value, "release trust record"); keys(input, ["releaseId", "jarvisVersion", "releaseSequence", "securityEpoch", "platform", "runtimeRole", "architecture", "sourceCommitSha", "artifactSha256", "tufTargetPath", "tufTargetMetadataVersion", "rollbackPolicy", "revoked"]); if (typeof input.sourceCommitSha !== "string" || !/^[a-f0-9]{40,64}$/u.test(input.sourceCommitSha)) throw new UpdateTrustValidationError("source commit SHA is invalid"); if (typeof input.revoked !== "boolean") throw new UpdateTrustValidationError("release revocation state is invalid"); return Object.freeze({ releaseId: id(input.releaseId, "releaseId"), jarvisVersion: text(input.jarvisVersion, "jarvisVersion"), releaseSequence: uint(input.releaseSequence, "releaseSequence"), securityEpoch: uint(input.securityEpoch, "securityEpoch"), platform: id(input.platform, "platform"), runtimeRole: id(input.runtimeRole, "runtimeRole"), architecture: id(input.architecture, "architecture"), sourceCommitSha: input.sourceCommitSha, artifactSha256: sha(input.artifactSha256, "artifactSha256"), tufTargetPath: text(input.tufTargetPath, "tufTargetPath"), tufTargetMetadataVersion: uint(input.tufTargetMetadataVersion, "tufTargetMetadataVersion"), rollbackPolicy: enumValue(input.rollbackPolicy, ["NORMAL_ONLY", "EXPLICIT_TRUSTED_TARGET"], "rollback policy"), revoked: input.revoked }); }
export function validateUpdateIncident(value: unknown): UpdateIncidentRecord { const input = record(value, "update incident"); keys(input, ["incidentId", "reason", "observedAt", "details"], ["releaseId"]); return Object.freeze({ incidentId: id(input.incidentId, "incidentId"), reason: enumValue(input.reason, ["UPDATE_TRUST_METADATA_EXPIRED", "UPDATE_ROOT_ROTATION_REQUIRED", "UPDATE_SIGNATURE_INVALID", "UPDATE_TARGET_REVOKED", "UPDATE_ROLLBACK_BLOCKED", "UPDATE_SECURITY_EPOCH_BLOCKED", "UPDATE_TRUST_ROOT_COMPROMISE_SUSPECTED", "MODULE_TARGET_REVOKED", "CATALOG_TRUST_UNAVAILABLE"], "incident reason"), ...(input.releaseId === undefined ? {} : { releaseId: id(input.releaseId, "releaseId") }), observedAt: timestamp(input.observedAt, "observedAt"), details: text(input.details, "details") }); }
export function validateUpdateOperation(value: unknown): UpdateOperationRecord { const input = record(value, "update operation"); keys(input, ["operationId", "kind", "state", "startedAt"], ["metadataRef", "completedAt", "failureReason"]); return Object.freeze({ operationId: id(input.operationId, "operationId"), kind: enumValue(input.kind, ["BACKUP", "UPDATE", "RECOVERY"], "operation kind"), state: enumValue(input.state, ["STARTED", "STAGED", "VERIFIED", "COMMITTED", "FAILED", "UNCERTAIN"], "operation state"), ...(input.metadataRef === undefined ? {} : { metadataRef: id(input.metadataRef, "metadataRef") }), startedAt: timestamp(input.startedAt, "startedAt"), ...(input.completedAt === undefined ? {} : { completedAt: timestamp(input.completedAt, "completedAt") }), ...(input.failureReason === undefined ? {} : { failureReason: text(input.failureReason, "failureReason") }) }); }
