import { validateDataPolicy } from "./execution-scope-runtime.mjs";
import type { ArtifactRecord, LeaseRecord, ProviderResumeReference, WorkerCheckpoint } from "./worker.ts";

export class WorkerStateValidationError extends Error {
  constructor(message: string) { super(message); this.name = "WorkerStateValidationError"; }
}
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new WorkerStateValidationError(`${label} must be an object`); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (Object.keys(value).some((key) => !allowed.has(key)) || required.some((key) => !(key in value))) throw new WorkerStateValidationError("worker record contains unsupported or missing fields"); }
function id(value: unknown, label: string): string { if (typeof value !== "string" || value.length < 1 || value.length > 256 || value.includes("\0")) throw new WorkerStateValidationError(`${label} is invalid`); return value; }
function text(value: unknown, label: string, max = 4096): string { if (typeof value !== "string" || value.length < 1 || value.length > max || value.includes("\0")) throw new WorkerStateValidationError(`${label} is invalid`); return value; }
function timestamp(value: unknown, label: string): string { const result = text(value, label, 64); if (Number.isNaN(Date.parse(result))) throw new WorkerStateValidationError(`${label} must be an ISO timestamp`); return result; }
function texts(value: unknown, label: string): readonly string[] { if (!Array.isArray(value) || value.length > 1024) throw new WorkerStateValidationError(`${label} is invalid`); return Object.freeze(value.map((item) => text(item, label))); }
function artifact(value: unknown): ArtifactRecord { const input = record(value, "artifact"); keys(input, ["artifactId", "logicalType", "contentType", "size", "producingAttemptId", "dataPolicy", "retention", "storageRef"], ["sha256", "projectId"]); if (!Number.isSafeInteger(input.size) || (input.size as number) < 0 || (input.size as number) > Number.MAX_SAFE_INTEGER) throw new WorkerStateValidationError("artifact size is invalid"); if (input.sha256 !== undefined && (typeof input.sha256 !== "string" || !/^[a-f0-9]{64}$/u.test(input.sha256))) throw new WorkerStateValidationError("artifact sha256 is invalid"); const policy = validateDataPolicy(input.dataPolicy); if (policy.sensitivity === "SECRET") throw new WorkerStateValidationError("secret content cannot enter the general artifact store"); return Object.freeze({ artifactId: id(input.artifactId, "artifactId"), logicalType: text(input.logicalType, "logicalType", 256), contentType: text(input.contentType, "contentType", 256), size: input.size as number, ...(input.sha256 === undefined ? {} : { sha256: input.sha256 }), producingAttemptId: id(input.producingAttemptId, "producingAttemptId"), ...(input.projectId === undefined ? {} : { projectId: id(input.projectId, "projectId") }), dataPolicy: policy, retention: text(input.retention, "retention", 128), storageRef: text(input.storageRef, "storageRef", 2048) }); }
function resume(value: unknown): ProviderResumeReference { const input = record(value, "provider resume"); keys(input, ["providerId", "handle", "createdAt"], ["providerVersion", "modelId", "lastVerifiedAt"]); return Object.freeze({ providerId: id(input.providerId, "providerId"), ...(input.providerVersion === undefined ? {} : { providerVersion: text(input.providerVersion, "providerVersion", 256) }), ...(input.modelId === undefined ? {} : { modelId: id(input.modelId, "modelId") }), handle: text(input.handle, "resume handle", 2048), createdAt: timestamp(input.createdAt, "createdAt"), ...(input.lastVerifiedAt === undefined ? {} : { lastVerifiedAt: timestamp(input.lastVerifiedAt, "lastVerifiedAt") }) }); }
export function validateArtifact(value: unknown): ArtifactRecord { return artifact(value); }
export function validateWorkerCheckpoint(value: unknown): WorkerCheckpoint { const input = record(value, "worker checkpoint"); keys(input, ["checkpointId", "taskId", "attemptId", "sequence", "createdAt", "goalSummary", "completedWork", "decisions", "findings", "artifacts", "verificationState", "currentActivity", "blockers", "liveStateAssumptions"], ["nextStep", "providerResume"]); if (!Number.isSafeInteger(input.sequence) || (input.sequence as number) < 1) throw new WorkerStateValidationError("checkpoint sequence is invalid"); if (!Array.isArray(input.artifacts) || input.artifacts.length > 1024 || !Array.isArray(input.verificationState) || input.verificationState.length > 1024) throw new WorkerStateValidationError("checkpoint evidence arrays are invalid"); return Object.freeze({ checkpointId: id(input.checkpointId, "checkpointId"), taskId: id(input.taskId, "taskId"), attemptId: id(input.attemptId, "attemptId"), sequence: input.sequence as number, createdAt: timestamp(input.createdAt, "createdAt"), goalSummary: text(input.goalSummary, "goalSummary"), completedWork: texts(input.completedWork, "completedWork"), decisions: texts(input.decisions, "decisions"), findings: texts(input.findings, "findings"), artifacts: Object.freeze(input.artifacts.map(artifact)), verificationState: Object.freeze(input.verificationState.map((item) => record(item, "verification state"))), currentActivity: text(input.currentActivity, "currentActivity"), ...(input.nextStep === undefined ? {} : { nextStep: text(input.nextStep, "nextStep") }), blockers: texts(input.blockers, "blockers"), liveStateAssumptions: texts(input.liveStateAssumptions, "liveStateAssumptions"), ...(input.providerResume === undefined ? {} : { providerResume: resume(input.providerResume) }) }); }
export function validateLease(value: unknown): LeaseRecord { const input = record(value, "lease"); keys(input, ["leaseId", "resourceType", "resourceId", "ownerInstanceId", "leaseType", "state", "acquiredAt", "heartbeatAt"], ["ownerTaskId", "ownerAttemptId"]); if (!Object.hasOwn({ ACTIVE: 1, RELEASED: 1, RECOVERY_REQUIRED: 1 }, String(input.state))) throw new WorkerStateValidationError("lease state is invalid"); if (input.ownerAttemptId !== undefined && input.ownerTaskId === undefined) throw new WorkerStateValidationError("lease attempt owner requires a task owner"); return Object.freeze({ leaseId: id(input.leaseId, "leaseId"), resourceType: id(input.resourceType, "resourceType"), resourceId: id(input.resourceId, "resourceId"), ownerInstanceId: id(input.ownerInstanceId, "ownerInstanceId"), ...(input.ownerTaskId === undefined ? {} : { ownerTaskId: id(input.ownerTaskId, "ownerTaskId") }), ...(input.ownerAttemptId === undefined ? {} : { ownerAttemptId: id(input.ownerAttemptId, "ownerAttemptId") }), leaseType: id(input.leaseType, "leaseType"), state: input.state as LeaseRecord["state"], acquiredAt: timestamp(input.acquiredAt, "acquiredAt"), heartbeatAt: timestamp(input.heartbeatAt, "heartbeatAt") }); }
